### ISSUE TITLE
adsbypasser dont work in http://sh.st/

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/Userscripts#7]
Hey,
the userscripts Adsbypasser (https://adsbypasser.github.io/)
dont work in site: http://sh.st/ with Adguard and need wait 5 seconds.
 with ‪Tampermonkey this yes work and no need  wait 5 seconds.
example:
http://sh.st/BrH0i

**Comment by ameshkov** [comment]
Most likely it is due to the rule added by @Alex-302:
https://github.com/AdguardTeam/AdguardForWindows/issues/1313#issuecomment-254049314

This rule disables all AG extensions.

**Comment by MrTal** [comment]
@ameshkov 
no can fix it?
